

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file: .env

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: erp_system
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
